
### 상품 목록 조회
GET http://localhost:3000/products

### 상품 등록
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "노트북",
  "description": "좋은 노트북",
  "price": 1200000,
  "tags": ["전자기기", "노트북"]
}

### 상품 상세 조회
GET http://localhost:3000/products/6a00470d47fb540515d3e6ab

### 상품 수정
PATCH http://localhost:3000/products/6a00470d47fb540515d3e6ab
Content-Type: application/json

{
  "price": 1000000
}

### 상품 삭제
DELETE http://localhost:3000/products/6a0040edf3a209b928cb69d6

### 검색 테스트
GET http://localhost:3000/products?keyword=노트북


### 상품 등록 2
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "마우스",
  "description": "좋은 마우스",
  "price": 30000,
  "tags": ["전자기기", "마우스"]
}

### 상품 등록 3
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "키보드",
  "description": "좋은 키보드",
  "price": 80000,
  "tags": ["전자기기", "키보드"]
}

### 상품 등록 4
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "모니터",
  "description": "좋은 모니터",
  "price": 350000,
  "tags": ["전자기기", "모니터"]
}

### 상품 등록 5
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "헤드셋",
  "description": "좋은 헤드셋",
  "price": 89000,
  "tags": ["전자기기", "헤드셋"]
}

### 정렬 페이지네이션 테스트
GET http://localhost:3000/products?page=1&pageSize=10&orderBy=recent

### 페이지네이션 테스트 2
GET http://localhost:3000/products?page=1&pageSize=2&orderBy=recent

### 페이지네이션 테스트 3
GET http://localhost:3000/products?page=2&pageSize=2&orderBy=recent

### 상품 목록 조회 테스트 2
GET http://localhost:3000/products?page=1&pageSize=10&orderBy=recent

### 상품 상세 조회 테스트 2
GET http://localhost:3000/products/6a004cee72795dde20e40ac2


### 상품 추가 테스트
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "테스트 상품입니다.",
  "description": "테스트 설명입니다.",
  "price": 10000,
  "tags": ["테스트"]
}


### 상품 상세 조회
GET http://localhost:3000/products/6a0a6d3a3ada29d98c854728
